name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup node
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Configure Git for commit (before deploy)
      - name: Configure Git for commit
        run: |
          git config --global user.name "Goncalo's Actions Bot"
          git config --global user.email "goncalvideira@hotmail.com"

      # Step 5: Deploy the application with authenticated push
      - name: Deploy
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          npm run deploy
        env:
          REACT_APP_AIRTABLE_API: ${{ secrets.AIRTABLE_API }}
          REACT_APP_SECRET_PASSWORD: ${{ secrets.SECRET_PASSWORD }}
          REACT_APP_BASE_ID: ${{ secrets.BASE_ID }}
