name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Configure Git for commit
        run: |
          git config --global user.name "Goncalo's Actions Bot"
          git config --global user.email "goncalvideira@hotmail.com"

      - name: Deploy
        run: npm run deploy
        env:
          REACT_APP_AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
